### ISSUE TITLE
Plugin now unusable due to typedoc change+bug: need to remove @Option

### ISSUE THREAD

**Issue by BobKerns** [kamiazya/typedoc-plugin-mermaid#123]
**Describe the bug**
In src/plugin.ts, the following appears:
```
  @Option({
    name: 'mermaidVersion',
    short: 'mmv',
    defaultValue: '7.1.2',
    help: 'Mermaid Plugin: Version of mermaid.js.',
    type: ParameterType.String,
  })
```
Unfortunately, `@Option` has been deprecated and slated to be removed in typedoc 0.17.
Even worse, it is broken in 0.16.9! This prevents your module from loading in 0.16.9

I tried to work around it by setting `mermaidVersion` in `typedoc.json`, but it didn't work. (I didn't expect it to).

**To Reproduce**

* Upgrade to typedoc 0.16.9
* Install typedoc-plugin-mermaid@latest
* Run typedoc
* Get the results below

**Expected behavior**
Successful run

**Failing output**
```
The @Option decorator is deprecated and will be removed in v0.17.
  (Used to register mermaidVersion)
Loaded plugin /Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc-plugin-mermaid
Loaded plugin /Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc-plugin-npm-externals

Using TypeScript 3.7.5 from /Users/rwk/p/npm-typescript-rollup-template/node_modules/typescript/lib
Skipping detailed PlantUml-Generation.
/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/utils/options/sources/decorator.js:19
                    return this.application.options.getValue(name);
                                                             ^

ReferenceError: name is not defined
    at MermaidPlugin.get [as mermaidVersion] (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/utils/options/sources/decorator.js:19:62)
    at MermaidPlugin.get customScriptsAndBodyClosinngTag [as customScriptsAndBodyClosinngTag] (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc-plugin-mermaid/dist/plugin.js:21:37)
    at MermaidPlugin.convertPageContents (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc-plugin-mermaid/dist/plugin.js:61:66)
    at MermaidPlugin.onPageEnd (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc-plugin-mermaid/dist/plugin.js:83:34)
    at triggerEvents (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/utils/events.js:128:43)
    at triggerApi (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/utils/events.js:110:13)
    at eventsApi (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/utils/events.js:21:18)
    at Renderer.trigger (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/utils/events.js:264:13)
    at Renderer.renderDocument (/Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/output/renderer.js:49:14)
    at /Users/rwk/p/npm-typescript-rollup-template/node_modules/typedoc/dist/lib/output/renderer.js:36:22
```

**Additional context**
I didn't bother to report it to typedoc, since they plan to remove it anyway in their next release, so that would be their fix, and you'll still have to change your code.

**Comment by BobKerns** [comment]
It seems the only reasonable workaround is to roll back typedoc-plugin-mermaid to 1.0.0, and be sure not to set mermaidVersion anywhere.

Rolling back typedoc breaks typedoc-plugin-mermaid with an undefined function at 0.16.3.

May I suggest adding integration tests with a matrix of different typedoc versions including @latest?  I'm going to look at doing the same for my own modest plugins.

BTW, it looks like typedoc is just changing the name, not deleting the feature?

**Comment by kamiazya** [comment]
@BobKerns 

Thanks for reporting.

Improve to be able to guarantee that the latest version works.

For now, delete the part that uses @Option.

**Comment by kamiazya** [comment]
@all-contributors please add @BobKerns  for bug
