### ISSUE TITLE
Breaking change after upgrade to typedoc 0.23.1

### ISSUE THREAD

**Issue by juergenzimmermann** [kamiazya/typedoc-plugin-mermaid#616]
**Describe the bug**
After upgrading to _typedoc 0.23.1_ I get the stacktrace below

**To Reproduce**
`npm i -D typedoc`

**Expected behavior**
No stacktrace.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Version: 21H2

**Additional context**
Stacktrace:
```
TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'replace')
    at MermaidPlugin.handleMermaidCodeBlocks (C:\workspace\software-engineering\buch\node_modules\typedoc-plugin-mermaid\dist\index.js:163:21)
    at MermaidPlugin.onConverterResolveBegin (C:\workspace\software-engineering\buch\node_modules\typedoc-plugin-mermaid\dist\index.js:135:37)
    at Converter.<anonymous> (C:\workspace\software-engineering\buch\node_modules\typedoc-plugin-mermaid\dist\index.js:119:18)
    at triggerEvents (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\utils\events.js:191:43)
    at triggerApi (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\utils\events.js:167:13)
    at eventsApi (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\utils\events.js:60:18)
    at Converter.trigger (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\utils\events.js:389:13)
    at Converter.resolve (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\converter\converter.js:123:14)
    at Converter.convert (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\converter\converter.js:39:14)
    at Application.convert (C:\workspace\software-engineering\buch\node_modules\typedoc\dist\lib\application.js:151:40)
```

**Comment by kamiazya** [comment]
@all-contributors please add @juergenzimmermann for bug
